<?php include_once('application/views/HeaderAdminView.phtml'); ?>

<main id='admin'>

    <h2> Administration </h2>

    <div class="flex-row">
        <section>
            <h3> Liste des derniers articles publiés</h3>

            <?php if (count($this->showArticles) === 0) : ?>
                <article>
                    <p> Vous n'avez pas encore d'article. </p>
                </article>
            <?php else : ?>
                <?php for ($i = 0; $i < count($this->showArticles); $i++) : ?>
                    <article>
                        <h4> <?= htmlspecialchars($this->showArticles[$i]['title']) ?> </h4>
                        "<?= strip_tags(substr($this->showArticles[$i]['content'], 0, 400)) ?>..."
                        <p class='italic'> Publié
                            <?php if ($_SESSION['user']['status'] == 'admin') : ?>
                                par <?= htmlspecialchars($this->showArticles[$i]['author']) ?>
                            <?php endif ?>
                            le <?= date("d/m/Y", strtotime($this->showArticles[$i]['date'])) ?>
                        </p>
                    </article>
                    <?php if ($i == 9) exit() ?>
                <?php endfor ?>
            <?php endif ?>
        </section>

        <section>
            <h3> Liste des derniers commentaires publiés </h3>

            <?php if ($_SESSION['user']['status'] == 'admin') : ?>
                <?php for ($i = 0; $i < count($this->showAllComments); $i++) : ?>
                    <article>
                        <h4> <?= htmlspecialchars($this->showAllComments[$i]['article_id']) ?> </h4>
                        <?php if (strlen($this->showAllComments[$i]['content']) > 100) : ?>
                            <p>"<?= substr(htmlspecialchars($this->showAllComments[$i]['content']), 0, 100) ?>..."</p>
                        <?php else : ?>
                            <p>"<?= substr(htmlspecialchars($this->showAllComments[$i]['content']), 0, 100) ?>"</p>
                        <?php endif ?>
                        <p class='italic'> Publié
                            par <?= htmlspecialchars($this->showAllComments[$i]['author']) ?>
                            le <?= date("d/m/Y", strtotime($this->showAllComments[$i]['date'])) ?>
                        </p>
                    </article>
                    <?php if ($i == 5) exit() ?>
                <?php endfor ?>
            <?php else : ?>
                <?php if (count($this->showCommentsFromAuthor) === 0) : ?>
                    <article>
                        <p> Vous n'avez pas encore de commentaire. </p>
                    </article>
                <?php else : ?>
                    <?php for ($i = 0; $i < count($this->showCommentsFromAuthor); $i++) : ?>
                        <article>
                            <h4> <?= htmlspecialchars($this->showCommentsFromAuthor[$i]['article_id']) ?> </h4>
                            <?php if (strlen($this->showCommentsFromAuthor[$i]['content']) > 100) : ?>
                                <p>"<?= substr(htmlspecialchars($this->showCommentsFromAuthor[$i]['content']), 0, 100) ?>..."</p>
                            <?php else : ?>
                                <p>"<?= substr(htmlspecialchars($this->showCommentsFromAuthor[$i]['content']), 0, 100) ?>"</p>
                            <?php endif ?>
                            <p class='italic'> Publié
                                par <?= htmlspecialchars($this->showCommentsFromAuthor[$i]['author']) ?>
                                le <?= date("d/m/Y", strtotime($this->showCommentsFromAuthor[$i]['date'])) ?>
                            </p>
                        </article>
                        <?php if ($i == 5) exit() ?>
                    <?php endfor ?>
                <?php endif ?>
            <?php endif ?>
        </section>
    </div>


</main>