<?php include_once('application/views/HeaderAdminView.phtml'); ?>

<main id='admin'>

    <h2> Administration </h2>

    <section>

        <h3> Liste des derniers articles publiés </h3>

        <?php for ($i = 0; $i < count($this->showArticles); $i++): ?>
        <article>
            <h4> <?=$this->showArticles[$i]['title']?> </h4>
            <?=$this->showArticles[$i]['content']?>          
            <p class='italic'> Publié 
                <?php if ($_SESSION['user']['status'] == 'admin'): ?>
                    par <?=$this->showArticles[$i]['author']?> 
                <?php endif ?>
                    le <?=$this->showArticles[$i]['date']?> 
            </p>
        </article>
        <?php if ($i == 4) exit() ?>
        <?php endfor ?>
    </section>


</main>