<body>

    <?php include_once('application/views/HeaderUserView.phtml') ?>

    <main id="articles">

        <section>

            <h2> Liste des articles publiés </h2>

            <?php for ($i = 0; $i < count($this->showArticles); $i++) : ?>
                <article>
                    <a href="articleDetails&id=<?= $this->showArticles[$i]['id'] ?>">
                        <h4> <?= htmlspecialchars($this->showArticles[$i]['title']) ?>
                            <?php if ($this->showArticles[$i]['category'] !== "") : ?>
                                <small class='italic'>(<?= htmlspecialchars($this->showArticles[$i]['category']) ?>)</small>
                            <?php endif ?>
                        </h4>
                    </a>
                    <div id="resumeContent">
                        <?= strip_tags(substr($this->showArticles[$i]['content'], 0, 700)) ?>
                        ...
                    </div>
                    <p class='italic'> Publié
                        par <?= htmlspecialchars($this->showArticles[$i]['author']) ?>
                        le <?= date("d/m/Y", strtotime(htmlspecialchars($this->showArticles[$i]['date']))) ?>
                    </p>
                </article>
                <hr>
            <?php endfor ?>
        </section>

    </main>

</body>