<body>

    <?php include_once('application/views/HeaderUserView.phtml') ?>

    <main id="articleDetails">

        <section>

            <h2> <?= htmlspecialchars($this->showArticleDetails['title'])?> </h2>
            <article id='articleContent'><?= $this->showArticleDetails['content']?></article>
            
            <p class='italic'> Publié 
                    par <?= htmlspecialchars($this->showArticleDetails['author'])?> 
                    le <?=$this->showArticleDetails['date']?> 
            </p>
            <hr>

        </section>

        <section id='comments'>

            <h3> Commentaires </h3>
            
            <?php for ($i = 0; $i < count($this->showComments); $i++): ?>
            <article>
                <h4>Par <?= htmlspecialchars($this->showComments[$i]['author'])?></h4>
                <p> <?= htmlspecialchars($this->showComments[$i]['content'])?> </p>
                <p class='italic'> Le <?=$this->showComments[$i]['date']?></p>
            </article>
            <hr>
            <?php endfor ?>

        </section>

        <section>

            <form action="addComment?articleId=<?=$this->showArticleDetails['id']?>" method="POST">

                <fieldset>
                    <legend>Laisser un petit commentaire pour l'auteur !</legend>
                    <ul>
                        <li>
                            <label for="comment">Nouveau commentaire : </label>
                            <textarea name="comment" id="comment" rows="10" cols="70" placeholder="Ecrivez un nouveau commentaire !"></textarea>
                        </li>
                        <li>
                            <label for="nickname">Pseudo :</label>
                            <input type="text" name="nickname" id="nickname">
                        </li>
                    </ul>                    
                </fieldset>

                <button type="submit">Publier</button>
            </form>

        </section>

    </main>
</body>