<?php include_once('application/views/HeaderAdminView.phtml'); ?>

<main id='listArticles' class="tableAdmin">

    <h2>Liste des articles</h2>

    <h3><a href='upsertArticle'> <i class="fas fa-plus-circle"></i> Créer un nouvel article </a></h3>

    <table>
        <thead>
            <tr>
                <th>Titre</th>
                <th>Catégorie</th>
                <th>Date de publication</th>
                <?php if ($_SESSION['user']['status'] == 'admin') : ?>
                    <th>Auteur</th>
                <?php endif ?>
                <th></th>
            </tr>
        </thead>
        <tbody>
            <?php for ($i = 0; $i < count($this->showArticles); $i++) : ?>
                <tr>
                    <td><?= $this->showArticles[$i]['title'] ?></td>
                    <td><?= $this->showArticles[$i]['category'] ?></td>
                    <td><?= $this->showArticles[$i]['date'] ?></td>
                    <?php if ($_SESSION['user']['status'] == 'admin') : ?>
                        <td><?= $this->showArticles[$i]['author'] ?></td>
                    <?php endif ?>
                    <td>
                        <?php if ($_SESSION['user']['nickname'] == $this->showArticles[$i]['author'] || $_SESSION['user']['id'] == $this->showArticles[$i]['author']) : ?>
                            <a href="upsertArticle&id=<?= $this->showArticles[$i]['id'] ?>"><i class="fas fa-edit"></i></a>
                        <?php endif ?>
                        <a class='delete-article' href="deleteArticle&deleteId=<?= $this->showArticles[$i]['id'] ?>"><i class="fas fa-trash-alt"></i></a>
                    </td>
                </tr>
            <?php endfor ?>
        </tbody>
    </table>

</main>