<?php include_once('application/views/HeaderAdminView.phtml'); ?>

<main id='listComments' class="tableAdmin">

    <h2>Liste des commentaires</h2>

    <table>
        <thead>
            <tr>
                <th>Article</th>
                <th>Nombre de commentaires</th>
            </tr>
        </thead>
        <tbody>
            <?php for ($i = 0; $i < count($this->showOwnArticles); $i++) : ?>
                <tr>
                    <td><a href="detailsComment&id=<?= $this->showOwnArticles[$i]['id'] ?>"><?= $this->showOwnArticles[$i]['title'] ?></a></td>
                    <td><?= $this->showOwnArticles[$i]['comments'] ?></td>
                </tr>
            <?php endfor ?>
        </tbody>
    </table>