<body>
    <?php include_once('application/views/HeaderUserView.phtml') ?>

    <main id="contact">

        <h2>Contact</h2>

        <section class="flex-column">
            <article>
                <p>Si vous rencontrez le moindre problème sur notre site ou souhaitez simplement contacter les administrateurs, n'hésitez pas à nous joindre à ces adresses. Nous vous répondrons dans les plus brefs délais.</p>
            </article>
            <article>
                <ul class="flex-row">
                    <li><a href="#"><i class="fab fa-facebook"></i>level_up</a></li>
                    <li><a href="#"><i class="fab fa-twitter-square"></i>@levelup</a></li>
                    <li><a href="#"><i class="fab fa-github"></i>level_up</a></li>
                    <li><a href="#"><i class="far fa-envelope"></i>level_up@gmail.com</a></li>
                </ul>
            </article>
        </section>

    </main>
</body>