<header>
    <nav class="flex-row">
        <i class="fas fa-bars headerResponsiveBar notshow"></i>
        <div class="imageHeader show">
            <h1> Level up <i class="fas fa-level-up-alt"></i> <span class="br">Your Life</span></h1>
        </div>
        <div class="navBar show">
            <a href='home'> Retour sur le site </a>
            <a href='admin'> Accueil </a>
            <?php if ($_SESSION['user']['status'] == 'admin') : ?>
                <a href='listUsers'> Gérer les utilisateurs </a>
                <a href='listArticles'> Gérer les articles </a>
                <a href='listCategories'> Gérer les catégories </a>
            <?php else : ?>
                <a href='listArticles'> Gérer vos articles </a>
            <?php endif ?>
            <a href='listComments'> Gérer vos commentaires </a>
            <a href='logout'> Déconnexion </a>
        </div>
    </nav>

</header>