<?php include_once('application/views/HeaderUserView.phtml'); ?>

<main id='home'>

    <section>

        <article>
            <h2>Reprenez le contrôle <span class='br'>de votre vie</span></h2>
        </article>

        <article class='flex-row thumbnail'>
            <p>Des articles permettant de vous aider à progresser dans votre lutte contre la procrastination
                <i class="fas fa-chart-line br"></i>
            </p>
            <p>Un calendrier intéractif permettant de concrétiser vos objectifs en temps voulu.
                <i class="fas fa-clock br"></i>
            </p>
            <p>Un système de récompense afin de vous motiver à continuer vos efforts
                <i class="fas fa-hand-holding-usd br"></i>
            </p>
        </article>

        <article>
            <h3>Derniers articles publiés par nos auteurs</h3>

            <div>
                <?php for ($i = 0; $i < count($this->showArticles); $i++) : ?>
                    <a href="articleDetails&id=<?= $this->showArticles[$i]['id'] ?>">
                        <h4> <?= htmlspecialchars($this->showArticles[$i]['title']) ?> </h4>
                    </a>
                    <p class='italic'>Publié le <?= date("d/m/Y", strtotime(htmlspecialchars($this->showArticles[$i]['date']))) ?></p>
                    <?php if ($i == 4) exit() ?>
                    <hr>
                <?php endfor ?>
            </div>

        </article>

    </section>

</main>

<?php include_once('application/views/FooterView.phtml'); ?>