<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>LifeControl</title>
    <!-- Externals links -->
    <link href="https://fonts.googleapis.com/css?family=Lemonada&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=EB+Garamond&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Podkova&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/a60fbf1630.js" crossorigin="anonymous"></script>
    <!-- Calender Links and Scripts -->
    <link href='application/views/js/fullcalendar/packages/core/main.css' rel='stylesheet' />
    <link href='application/views/js/fullcalendar/packages/daygrid/main.css' rel='stylesheet' />
    <script src='application/views/js/fullcalendar/packages/core/main.js'></script>
    <script src='application/views/js/fullcalendar/packages/core/locales/fr.js'></script>
    <script src='application/views/js/fullcalendar/packages/daygrid/main.js'></script>
    <script src='application/views/js/fullcalendar/packages/interaction/main.js'></script>
    <!-- TinyMCE Script -->
    <script src="https://cdn.tiny.cloud/1/0neezv86dwl23u2gwnb2vltajdd17hqn6oqk0fcq5pnbqbmb/tinymce/5/tinymce.min.js" referrerpolicy="origin"></script>
    <!-- CSS Links -->
    <link rel="stylesheet" type="text/css" href="application/views/css/reset.css">
    <link rel="stylesheet" type="text/css" href="application/views/css/style.css">
    <!-- JS Script -->
    <script src="application/views/js/calendar.js"></script>
    <script src="application/views/js/admin.js"></script>
    <script src="application/views/js/register.js"></script> 
</head>
