<body>
    <?php include_once('application/views/HeaderUserView.phtml'); ?>

    <main id="editPassword">

        <h2>Modification de votre profil</h2>

        <form id="register" method="POST" action="editPassword&updatePassword">

            <?php if (!empty($this->errors)) : ?>
                <?php foreach ($this->errors as $error) : ?>
                    <p class="error"> <?= $error; ?> </p>
                <?php endforeach; ?>
            <?php endif; ?>

            <fieldset>
                <ul id="formFields">
                    <li>
                        <label for="oldPassword"> Votre mot de passe actuel : </label>
                        <input type="password" name="oldPassword" id="oldPassword">
                        <p></p>
                    </li>
                    <li>
                        <label for="newPassword"> Votre nouveau mot de passe : </label>
                        <input type="password" name="newPassword" id="newPassword">
                        <p></p>
                    </li>
                    <li>
                        <label for="confirmationPassword"> La confirmation de votre nouveau mot de passe : </label>
                        <input type="password" name="confirmationPassword" id="confirmationPassword">
                        <p></p>
                    </li>
                </ul>
            </fieldset>

            <button type="submit" class="submit">Modifier votre mot de passe</button>
            <button type="reset" class="erase">Effacer les informations</button>

        </form>

    </main>
</body>